### ISSUE TITLE
Easy way to add multiple autocomplete

### ISSUE THREAD

**Issue by programever** [futureworkz/elm-autocomplete#3]
**Target:** 
One autocompleteState for multiple autocomplete field

**Issue:**
- The issue come from Fetcher
- Fetcher need to receive more information in order to fetch correct data from API

**Temporary Solution:**
- Duplicate the autocompleteState with different fetchers

**Comment by stevenyap** [comment]
I think it's better to hold different autocomplete for different fields. We can't assume the behaviour of different fields to be the same.

**Comment by programever** [comment]
Yah, seem like all other packages facing the same issue!
I will close this!

**Comment by stevenyap** [comment]
I don't see this as an issue, I see it more like an anti-pattern of holding a single autocomplete for multiple different autocomplete fields.... My opinion is towards a pattern of one autocomplete state for one autocomplete field which is more verbose in codes but has the advantage of separation of concerns.

Thanks for closing the issue!
