### ISSUE TITLE
Beginner question: usage with nested state

### ISSUE THREAD

**Issue by weiss-d** [futureworkz/elm-autocomplete#6]
Hi and thanks for this library!
I used it normally until I decided to separate a state of a form from everything else on the page, therefore creating a 'submodel' and a subset of messages for it.
Here's what I did illustrated on your example file:
```Elm
type alias InputModel =
    { -- Add Autocomplete state to your model
      autocompleteState : Autocomplete String

    -- (Optional) final selected value from user
    , selectedValue : Maybe String
    }


type alias Model =
    { inputModel : InputModel }


type InputMsg
    = -- Autocomplete Msg
      OnAutocomplete (Autocomplete.Msg String)
      -- Your msg to be emitted when user selects a value
    | OnAutocompleteSelect
      -- (Optional) Your msg to be emitted on blur (to close autocomplete)
    | OnAutocompleteBlur


type Msg
    = InputMsg InputMsg
```

Now I'm getting type error practically saying that `AutocompleteView.events` now generates `ImputMsg` events instead of `Msg`.

I tried to pass messages like this
```Elm
{ inputEvents, choiceEvents } =
            AutocompleteView.events
                { onSelect = InputMsg OnAutocompleteSelect
                , mapHtml = InputMsg OnAutocomplete
                }
```
but it obviously doesn't work.

What should I do to resolve this problem? 

Full code and error traceback are in this gist: https://gist.github.com/weiss-d/19f4050d2759bd61b1e9ee7790bbf0a8

**Comment by stevenyap** [comment]
Based on your type, you nested `OnAutoComplete` into `InputMsg`.

When you try to pass `InputMsg OnAutocomplete`, it is actually an invalid code because that type is malformed as it requires one more argument to complete it (eg. `Autocomplete.Msg String`).

The correct way is to pass `InputMsg << OnAutocomplete` (note the `<<`).
`InputMsg << OnAutocomplete` is a "function" takes an `Autocomplete.Msg String` and creates a final `InputMsg (OnAutocomplete (Autocomplete.Msg String)`.

This now fits what `mapHtml` requires:
https://github.com/futureworkz/elm-autocomplete/blob/a90d52c261e0e6148e89c31fdd0428b9f3ca71f6/src/Autocomplete/View.elm#L100-L112

So this should fix your problem:
```elm
{ inputEvents, choiceEvents } =
            AutocompleteView.events
                { onSelect = InputMsg OnAutocompleteSelect
                , mapHtml = InputMsg << OnAutoComplete -- Add << here
                }
```

FYI In case you are new to Elm, Union types (and also Record types!) works like functions... just like the example above.

**Comment by weiss-d** [comment]
Hi @stevenyap !
Yeah, about 2 weeks in Elm :) I felt like I'm missing something fundamental, but just couldn't grasp it. Thank you for the clarification.

Although error is gone, the status now is always stuck on `Autocomplete.Fetching`. Am I missing something else?

**Comment by stevenyap** [comment]
Try throwing around some `_ = Debug.log "test" "here"` in your code to see what went wrong... if you still can't solve it, post your new code here... it's probably something to do with your `fetcher` or your logic in your model...

Welcome to Elm! It's a really enjoyable language! The beginning is rough but you will LOVE it once everything finally 'clicked' in your head! 😄

**Comment by weiss-d** [comment]
Oh, well, that was a dumb mistake: when nesting update function I've ignored the fact, that it may return a command.

Now `update` looks like this:
```Elm
update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        InputMsg inputMsg ->
            let
                ( newInputModel, newCmd ) =
                    updateInput inputMsg model.inputModel
            in
            ( { model | inputModel = newInputModel }, Maybe.withDefault Cmd.none newCmd )
```
And `updateInput`:
```Elm
updateInput : InputMsg -> InputModel -> ( InputModel, Maybe (Cmd InputMsg) )
updateInput msg inputModel =
    case msg of
        -- This is the main wire-up to pass Autocomplete Msg to Autocomplete state
        OnAutocomplete autocompleteMsg ->
            let
                ( newAutocompleteState, autoCompleteCmd ) =
                    Autocomplete.update autocompleteMsg inputModel.autocompleteState
            in
            ( { inputModel | autocompleteState = newAutocompleteState }
            , Just (Cmd.map OnAutocomplete autoCompleteCmd)
            )
-- ... the rest of the branches ...
```

But I have no idea how to convert `Cmd InputMsg` from `updateInput` to `Cmd Msg` in this context. Could you suggest something please?

Also updated [the gist](https://gist.github.com/weiss-d/19f4050d2759bd61b1e9ee7790bbf0a8) with full code and current error message.

**Comment by stevenyap** [comment]
Great job in finding out the bug!

To map your `Cmd`, here's a hint:

Given `type Msg = Wrapper InputMsg` and you have a `InputMsg`,
then to make it into a `Msg`,
you can use `Cmd.map Wrapper InputMsg`
or simply `Wrapper InputMsg` (remember `Wrapper` is a function  😉)

Also, there is no need to use `Maybe` for your `Cmd`.
If you don't have a `Cmd` to execute, simply return `Cmd.none` which is a `Cmd` that does nothing.
This saves you the trouble of casing out `Maybe`.

Hope this helps!

BTW there is https://elm-lang.org/community/slack and https://discourse.elm-lang.org/ where you can post your code to ask for help. The community is very very helpful and friendly so it's good to get in touch with them.

**Comment by weiss-d** [comment]
Ok, I see, I just can return `Cmd Msg` instead of `Cmd InputMsg` from nested update function and convert inside this function. Not sure if what I've made is beautiful, but it did the job 😄. Updated the gist in case someone stumbles upon this thread.

While I feel like public slacks are somewhat overloaded, I'll definitely check out discoruse.

Big thanks again for all the tips!
